---
name: XML-GenericJSON
version: 0.05
author:
  - 'Mark Howe <melonman@cpan.org>'
abstract: for turning XML into JSON, preserving as much XMLness as possible.
license: bsd
requires:
  JSON::XS: 0
  XML::LibXML: 1.58
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.34
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  XML::GenericJSON:
    file: lib/XML/GenericJSON.pm
    version: 0.05
resources:
  license: http://opensource.org/licenses/bsd-license.php
